### ISSUE TITLE
Training interrupts with error

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#514]
Version 4.2.

`It happened again.

@nicolabertoldi

` ./mmt create zh nl data/procdut -e procdut --debug --tensorboard-port 8066
/home/loek/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/loek/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/loek/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/loek/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/loek/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/loek/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])

=========== TRAINING STARTED ===========

ENGINE: procdut
LANGUAGE: zh > nl

(1/4) Cleaning corpora
(1/6) Cleaning corpora... DONE in 0s
(2/6) De-duplicate corpora... DONE in 0s
(3/6) Preprocess corpora... DONE in 0s
(4/6) Creating aligner filter... DONE in 0s
(5/6) Scoring corpora... DONE in 0s
(6/6) Apply aligner-based filter... DONE in 0s
(1/4) Cleaning corpora DONE in 2s
(2/4) Creating engine
(2/4) Creating engine DONE in 0s
(3/4) Generating binary archives
(1/4) Tokenize corpora... DONE in 0s
(2/4) Training BPE model... DONE in 3s
(3/4) Encoding training corpora... DONE in 0s
(4/4) Generating binary data... DONE in 0s
(3/4) Generating binary archives DONE in 5s
(4/4) Training neural model
(1/2) Train neural network...
ERROR Unexpected exception: Command 'fairseq-train /home/loek/modernmt2/runtime/procdut/tmp/training/data_generated --save-dir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt2/build/mmt-4.2.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas (0.9, 0.98) --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10' failed with exit code 1`

**Comment by ecly** [comment]
Try running the command it says failed:
```bash
fairseq-train /home/loek/modernmt2/runtime/procdut/tmp/training/data_generated --save-dir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt2/build/mmt-4.2.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas (0.9, 0.98) --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10
```
on its own, such that the exception output isn't caught. Then you can see what Fairseq is complaining about. That is assuming that no temporary files have been deleted since then.

**Comment by LoekvanKooten** [comment]
It says bash: bash: syntax error near unexpected token `('

**Comment by ecly** [comment]
@LoekvanKooten this is not the actual error, but just a parse error for the `--adam-betas` option's values.
 Try removing that from the command, such that you are running:
```bash
fairseq-train /home/loek/modernmt2/runtime/procdut/tmp/training/data_generated --save-dir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt2/build/mmt-4.2.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10
```

then we should see that actual error instead.

**Comment by LoekvanKooten** [comment]
It continues training when I give that command. I'm not sure whether it will actually stop automatically now.

**Comment by nicolabertoldi** [comment]
using fairseq-train` directly
you have to use ''--max-updates" to set the maximum number of updates

**Comment by LoekvanKooten** [comment]
That still doesn't explain the error though. Why does the command work when given straight from bash, but not from ModernMT?

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

Actually I did not see the error message from fairseq-train

Wwhat do you get if you run the following command?

```
fairseq-train /home/loek/modernmt2/runtime/procdut/tmp/training/data_generated --save-dir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt2/build/mmt-4.2.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas '(0.9, 0.98)' --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10 --max-updates 2000
```

Are you using the latest version of ModernMT?

**Comment by LoekvanKooten** [comment]
That gives:
fairseq-train: error: unrecognized arguments: --max-updates 2000

I'm using 4.2, the latest version.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
sorry,

the right option is `--max-update`, as you can verify from the help, which you get by running `fairseq-train` without parameters.

**Comment by LoekvanKooten** [comment]
With that it just starts training.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

If the command `fairseq-train` works properly, the problem arises from somewhere else.

The error you reported was totally new for us, so I need some help for you to debug.

Are you sure that you are using the right software versions?
Please check using
```
pip show regex sacrebleu requests cachetools tensorboardX torch fairseq
```

The correct ones should be 
```
regex 2019.4.14
sacrebleu 1.3.1
requests 2.9.1
cachetools 3.0.0
tensorboardX 1.6
torch 1.0.1
fairseq 0.7.1
```

May I ask you to re-create from scratch a system using the example data
using the following command
```
./mmt    create    en    it    examples/data/train/    --engine DEBUG    --debug 
```

The idea is to re--produce the error, if any, in the easiest case.

If this succeeded, please try the same command on your data.
Remember to remove everything related to the previous engine both in `engines` and in `runtime`

**Comment by LoekvanKooten** [comment]
Requests seems to be old. The rest is newer.

pip3 show regex sacrebleu requests cachetools tensorboardX torch fairseq
Name: regex
Version: 2019.8.19
Summary: Alternative regular expression module, to replace re.
Home-page: https://bitbucket.org/mrabarnett/mrab-regex
Author: Matthew Barnett
Author-email: regex@mrabarnett.plus.com
License: Python Software Foundation License
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: 
---
Name: sacrebleu
Version: 1.3.4
Summary: Hassle-free computation of shareable, comparable, and reproducible BLEU scores
Home-page: https://github.com/mjpost/sacrebleu
Author: Matt Post
Author-email: post@cs.jhu.edu
License: Apache License 2.0
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: typing
---
Name: requests
Version: 2.22.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: certifi, chardet, urllib3, idna
---
Name: cachetools
Version: 3.1.1
Summary: Extensible memoizing collections and decorators
Home-page: https://github.com/tkem/cachetools
Author: Thomas Kemmer
Author-email: tkemmer@computer.org
License: MIT
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: 
---
Name: tensorboardX
Version: 1.6
Summary: TensorBoardX lets you watch Tensors Flow without Tensorflow
Home-page: https://github.com/lanpa/tensorboardX
Author: Tzu-Wei Huang
Author-email: huang.dexter@gmail.com
License: MIT license
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: protobuf, numpy, six
---
Name: torch
Version: 1.0.1.post2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: 
---
Name: fairseq
Version: 0.7.1
Summary: Facebook AI Research Sequence-to-Sequence Toolkit
Home-page: https://github.com/pytorch/fairseq
Author: None
Author-email: None
License: UNKNOWN
Location: /home/loek/.local/lib/python3.6/site-packages
Requires: torch, tqdm, cffi, sacrebleu, numpy

**Comment by LoekvanKooten** [comment]
(Training your sample model now.)

**Comment by LoekvanKooten** [comment]
The same error. Here goes:

`ERROR Unexpected exception: Command 'fairseq-train /home/loek/modernmt2/runtime/DEBUG/tmp/training/data_generated --save-dir /home/loek/modernmt2/runtime/DEBUG/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt2/build/mmt-4.2.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt2/runtime/DEBUG/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas (0.9, 0.98) --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10' failed with exit code 1
`

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

Actually, the issue seems arise from a mismatch among any of the your python modules.

Could you please report the full content of this logfile `runtime/DEBUG/logs/training.log`

Could you also check the version of `numpy`
```
pip3 show  numpy
```
my working version is 1.16

**Comment by LoekvanKooten** [comment]
Name: numpy
Version: 1.17.2
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/loek/.local/lib/python3.6/site-packages
Requires:

**Comment by LoekvanKooten** [comment]
Log file.
[training.log](https://github.com/modernmt/modernmt/files/3720955/training.log)

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
this error is definitely new.
It seems that there are too many open files.It seems that the system or the operating system does not close the filestream after its creation

Could you please check the content of this directory?
```
/home/loek/modernmt2/runtime/DEBUG/tmp/training/_temp_train/nn_model/
```

By the way, the error can probably overcome by setting this parameter
```
--no-epoch-checkpoints
```

**Comment by LoekvanKooten** [comment]
Before we go on,  could this be caused by the fact that I'm running six engines in another hash window?

13 okt. 2019 schreef:
>@LoekvanKooten 
>this error is definitely new.
>It seems that there are too many open files.It seems that the system or
>the operating system does not close the filestream after its creation
>
>Could you please check the content of this directory?
>```
>/home/loek/modernmt2/runtime/DEBUG/tmp/training/_temp_train/nn_model/
>```
>
>By the way, the error can probably overcome by setting this parameter
>```
>--no-epoch-checkpoints
>```

-- Verzonden van mijn Android telefoon met K-@ Mail.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

not sure.
but certainly this does not happen.

However, this should solve the error:
https://github.com/modernmt/modernmt/blob/master/INSTALL.md#troubleshooting-and-support

Just as a curiosity, could you please report which are the actual defaults?
You can get them by running
```
ulimit -a
```

**Comment by LoekvanKooten** [comment]
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 257327
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 257327
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by LoekvanKooten** [comment]
The contents of said directory are:
checkpoint_154_2000.pt	checkpoint485.pt  checkpoint492.pt
checkpoint_231_3000.pt	checkpoint486.pt  checkpoint493.pt
checkpoint_308_4000.pt	checkpoint487.pt  checkpoint_77_1000.pt
checkpoint_385_5000.pt	checkpoint488.pt  checkpoint_best.pt
checkpoint_462_6000.pt	checkpoint489.pt  checkpoint_last.pt
checkpoint483.pt	checkpoint490.pt
checkpoint484.pt	checkpoint491.pt

**Comment by LoekvanKooten** [comment]
I retrained with an adapted limits.conf

No luck. Same error.

**Comment by LoekvanKooten** [comment]
I retrained with an adapted limits.conf

No luck. Same error.

Is my limits.conf correct? Because even after a restart, ulimit still shows 1024 for nofiles. 
[limits.txt](https://github.com/modernmt/modernmt/files/3722431/limits.txt)

**Comment by LoekvanKooten** [comment]
--no-epoch-checkpoints

does not change anything either. I get the same error.

**Comment by LoekvanKooten** [comment]
Something which I find strange is this error continuously being reported by Tensorflow in another hash window:

W1013 22:54:27.637725 139933668935424 plugin_event_accumulator.py:557] Detected out of order event.step likely caused by a TensorFlow restart. Purging 1 expired tensor events from Tensorboard display between the previous step: 24 (timestamp: 1571000057.9876804) and current step: 0 (timestamp: 1571000063.1154892).

This is after completely cleaning runtime/engine dirs.

**Comment by LoekvanKooten** [comment]
I should also add I had no issues training engines with 4.0. This happened after installing 4.2.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

Sincerely, I do not understand what's wrong with your setting.

I would kindly ask you to:
- uninstall tensorflow and tensorboardX:
```
pip3 uninstall tensorflow tensorboardX
```
- re-install tensorboardX:
```
pip3 install tensorboardX
```
- kill all running engines and trainings
- check that no processes are running, using
```
ps -ef
```
- set the new limits or using this command 
```
ulimit -n 1048576
```
- remove all previous engines in `engines` and `runtime`
- re-start the training using this command:
```
mmt create en it example/data/train --engine DEBUG --debug --no-epoch-checkpoints
```

**Comment by LoekvanKooten** [comment]
pip3 uninstall tensorflow tensorboardX
Cannot uninstall requirement tensorflow, not installed

**Comment by LoekvanKooten** [comment]
Also:
sudo ulimit -n 1048576
[sudo] password for loek: 
sudo: ulimit: command not found

**Comment by LoekvanKooten** [comment]
BTW, fairseq now reports a different error:

fairseq-train /home/loek/modernmt/runtime/procdut/tmp/training/data_generated --save-dir /home/loek/modernmt/runtime/procdut/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /home/loek/modernmt/build/mmt-4.0.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /home/loek/modernmt/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10
Namespace(activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9, 0.999)', adam_eps=1e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, arch='transformer_mmt_base', attention_dropout=0.1, bucket_cap_mb=25, clip_norm=0.0, cpu=False, criterion='label_smoothed_cross_entropy', curriculum=0, data='/home/loek/modernmt/runtime/procdut/tmp/training/data_generated', dataset_impl='cached', ddp_backend='c10d', decoder_attention_heads=8, decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim=2048, decoder_input_dim=512, decoder_layers=6, decoder_learned_pos=False, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.3, encoder_attention_heads=8, encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=2048, encoder_layers=6, encoder_learned_pos=False, encoder_normalize_before=False, find_unused_parameters=False, fix_batches_to_gpus=False, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, global_sync_iter=10, keep_interval_updates=10, keep_last_epochs=10, label_smoothing=0.1, lazy_load=False, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=100, lr=[0.0005], lr_scheduler='inverse_sqrt', max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=3072, max_update=0, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, no_epoch_checkpoints=False, no_progress_bar=True, no_save=False, no_token_positional_embeddings=False, num_workers=0, optimizer='adam', optimizer_overrides='{}', raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='/home/loek/modernmt/runtime/procdut/tmp/training/_temp_train/nn_model', save_interval=1, save_interval_updates=1000, seed=1, sentence_avg=False, share_all_embeddings=True, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='mmt_translation', tbmf_wrapper=False, tensorboard_logdir='/home/loek/modernmt/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir', threshold_loss_scale=None, train_subset='train', update_freq=[4], upsample_primary=1, use_bmuf=False, user_dir='/home/loek/modernmt/build/mmt-4.0.jar/mmt', valid_subset='valid', validate_interval=1, warmup_init_lr=1e-07, warmup_updates=4000, weight_decay=0.0)
Traceback (most recent call last):
  File "/home/loek/.local/bin/fairseq-train", line 11, in <module>
    sys.exit(cli_main())
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 302, in cli_main
    main(args)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 42, in main
    task = tasks.setup_task(args)
  File "/home/loek/.local/lib/python3.6/site-packages/fairseq/tasks/__init__.py", line 19, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/home/loek/modernmt/build/mmt-4.0.jar/mmt/__init__.py", line 41, in setup_task
  File "/home/loek/modernmt/build/mmt-4.0.jar/mmt/textencoder.py", line 453, in load
  File "/home/loek/modernmt/build/mmt-4.0.jar/mmt/textencoder.py", line 447, in load
FileNotFoundError: [Errno 2] No such file or directory: '/model.vcb'

**Comment by LoekvanKooten** [comment]
As for the file limit, you want to read this:
https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu

There's a bug in Ubuntu that prevents you from changing it.

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

why are you using `mmt-4.0`?

I suspect that you have a completely mixed-up environment.
We and other users do not experience any of your problems.
You understand that, it is very hard to us to debug not having access to your machine.


I would kindly suggest you to work in a virtual environment.
In this way you can have always a "clean" environment.

Then, after checking the hardware requirements
https://github.com/modernmt/modernmt/blob/master/INSTALL.md#hardware-requirements,
you can follow carefully the instructions
https://github.com/modernmt/modernmt/blob/master/INSTALL.md#install-modernmt-from-source

and re-try to create an engine.

**Comment by LoekvanKooten** [comment]
Oh, actually I have both 4.0 and 4.2 installed, but 4.0 is now giving me the same error. They're both in separated directories. That's not it.

What may be the culprit is Tensorboard. When looking at data on port 6006, graphs were displayed and updated. This while I've been giving the command to display it at port 8066 for ages already, so this must be some really old stuff.

Reinstalling Tensorboard (using the above command without Tensorflow) solved that. The engine is now training. I'll let you know how it ends.

**Comment by LoekvanKooten** [comment]
Okay, this works.

Steps:
Reinstall Tensorboard
Kill runtime and engine directories
Don't use wrong flags when starting MMT (like --max-updates instead of --max-update)
Verify that you watch Tensorboard using the right port (in my case 8066 instead of 6006)
Riase ulimit circumventing the bug in Ubuntu (see above)
...
And probably a combination of all the above.

In this case, MMT did not stop the training automatically. Do you still have to watch the loss and stop the process yourself?

**Comment by LoekvanKooten** [comment]
Argh, too early!

Now I get:
ERROR Unexpected exception: could not find "loss" value in event file: /home/loek/modernmt2/runtime/procdut/tmp/training/_temp_train/tensorboard_logdir/valid/events.out.tfevents.1571036646.DORAEMON

**Comment by LoekvanKooten** [comment]
[events.out.tfevents.1571036646.DORAEMON.txt](https://github.com/modernmt/modernmt/files/3723308/events.out.tfevents.1571036646.DORAEMON.txt)

**Comment by LoekvanKooten** [comment]
This training can be resumed. It seems to be some kind of timing problem? Maybe caused by the fact that I'm running other engines in another bash at the same time? I'll have to try that once I can turn production off at the end of the day.

**Comment by LoekvanKooten** [comment]
I think this was probably a port issue with Tensorboard. By default Tensorboard uses port 6006, but for some reason I started the training on port 8066 and was watching 8066 too. So that's where the mixed environment comes in: apparently Tensorboard was using two ports at the same time, mixing up everything.

I now succesfully completed the training. 

One question remains:

In this case, MMT did not stop the training automatically. Do you still have to watch the loss and stop the process yourself?

**Comment by ecly** [comment]
@LoekvanKooten in newer version no - the model will stop training itself, so perhaps this issue should be closed now?

**Comment by aaraki** [comment]
Hello,I use colab.I'm trying to execute 
"!mmt/mmt create ja en -e mmt_ja-en mmt/examples/kftt/train --train-steps 10 --engine DEBUG --debug", 
then I get the following error.Could you teach me the solution?
when I set the "--no-epoch-checkpoints" parameter,I get the same error.

(4/4) Training neural model
    (1/2) Train neural network...                                
ERROR Unexpected exception: Command 'fairseq-train /content/mmt/runtime/DEBUG/tmp/training/data_generated --save-dir /content/mmt/runtime/DEBUG/tmp/training/_temp_train/nn_model --task mmt_translation --user-dir /content/mmt/build/mmt-4.5.4.jar/mmt --share-all-embeddings --no-progress-bar --tensorboard-logdir /content/mmt/runtime/DEBUG/tmp/training/_temp_train/tensorboard_logdir --dataset-impl mmap --max-update 10 --debug --arch transformer_mmt_base --clip-norm 0.0 --label-smoothing 0.1 --attention-dropout 0.1 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --optimizer adam --adam-betas (0.9, 0.98) --log-interval 100 --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 --warmup-init-lr 1e-07 --warmup-updates 4000 --max-tokens 3072 --update-freq 4 --save-interval-updates 1000 --keep-interval-updates 10 --keep-last-epochs 10' failed with exit code 2
